library verilog;
use verilog.vl_types.all;
entity dispatch_unit is
    generic(
        TAG_WIDTH       : integer := 6;
        \ROB_IDX\       : integer := 5
    );
    port(
        clk             : in     vl_logic;
        rst_n           : in     vl_logic;
        flush           : in     vl_logic;
        ren_valid       : in     vl_logic;
        dispatch_ready  : out    vl_logic;
        ren_rd          : in     vl_logic_vector(4 downto 0);
        ren_rs1         : in     vl_logic_vector(4 downto 0);
        ren_rs2         : in     vl_logic_vector(4 downto 0);
        ren_rs3         : in     vl_logic_vector(4 downto 0);
        ren_prd         : in     vl_logic_vector;
        ren_prs1        : in     vl_logic_vector;
        ren_prs2        : in     vl_logic_vector;
        ren_prs3        : in     vl_logic_vector;
        ren_old_prd     : in     vl_logic_vector;
        ren_imm         : in     vl_logic_vector(31 downto 0);
        ren_pc          : in     vl_logic_vector(31 downto 0);
        ren_use_rs1     : in     vl_logic;
        ren_use_rs2     : in     vl_logic;
        ren_use_rs3     : in     vl_logic;
        ren_use_rd      : in     vl_logic;
        ren_fp_rs1      : in     vl_logic;
        ren_fp_rs2      : in     vl_logic;
        ren_fp_rs3      : in     vl_logic;
        ren_fp_rd       : in     vl_logic;
        ren_to_alu      : in     vl_logic;
        ren_to_fpu      : in     vl_logic;
        ren_to_lsu      : in     vl_logic;
        ren_alu_op      : in     vl_logic_vector(4 downto 0);
        ren_fpu_op      : in     vl_logic_vector(4 downto 0);
        ren_lsu_op      : in     vl_logic_vector(2 downto 0);
        ren_is_branch   : in     vl_logic;
        ren_is_jal      : in     vl_logic;
        ren_is_jalr     : in     vl_logic;
        ren_is_lui      : in     vl_logic;
        ren_is_auipc    : in     vl_logic;
        ren_is_load     : in     vl_logic;
        ren_is_store    : in     vl_logic;
        ren_is_fp_load  : in     vl_logic;
        ren_is_fp_store : in     vl_logic;
        ren_branch_op   : in     vl_logic_vector(2 downto 0);
        rob_alloc_valid : out    vl_logic;
        rob_alloc_pc    : out    vl_logic_vector(31 downto 0);
        rob_alloc_rd_arch: out    vl_logic_vector(4 downto 0);
        rob_alloc_prd   : out    vl_logic_vector;
        rob_alloc_old_prd: out    vl_logic_vector;
        rob_alloc_fp_rd : out    vl_logic;
        rob_alloc_is_branch: out    vl_logic;
        rob_alloc_is_jump: out    vl_logic;
        rob_alloc_jump_rd_val: out    vl_logic_vector(31 downto 0);
        rob_alloc_is_store: out    vl_logic;
        rob_alloc_use_rd: out    vl_logic;
        rob_idx         : in     vl_logic_vector;
        rob_full        : in     vl_logic;
        iq_alu_wr_en    : out    vl_logic;
        iq_fpu_wr_en    : out    vl_logic;
        iq_lsu_wr_en    : out    vl_logic;
        iq_prd          : out    vl_logic_vector;
        iq_prs1         : out    vl_logic_vector;
        iq_prs2         : out    vl_logic_vector;
        iq_prs3         : out    vl_logic_vector;
        iq_prs1_ready   : out    vl_logic;
        iq_prs2_ready   : out    vl_logic;
        iq_prs3_ready   : out    vl_logic;
        iq_imm          : out    vl_logic_vector(31 downto 0);
        iq_pc           : out    vl_logic_vector(31 downto 0);
        iq_alu_op       : out    vl_logic_vector(4 downto 0);
        iq_fpu_op       : out    vl_logic_vector(4 downto 0);
        iq_lsu_op       : out    vl_logic_vector(2 downto 0);
        iq_rob_idx      : out    vl_logic_vector;
        iq_use_imm      : out    vl_logic;
        iq_is_branch    : out    vl_logic;
        iq_is_jal       : out    vl_logic;
        iq_is_jalr      : out    vl_logic;
        iq_is_lui       : out    vl_logic;
        iq_is_auipc     : out    vl_logic;
        iq_is_load      : out    vl_logic;
        iq_is_store     : out    vl_logic;
        iq_is_fp_load   : out    vl_logic;
        iq_is_fp_store  : out    vl_logic;
        iq_branch_op    : out    vl_logic_vector(2 downto 0);
        iq_fp_rd        : out    vl_logic;
        iq_fp_rs1       : out    vl_logic;
        iq_fp_rs2       : out    vl_logic;
        iq_alu_full     : in     vl_logic;
        iq_fpu_full     : in     vl_logic;
        iq_lsu_full     : in     vl_logic;
        prf_int_ready   : in     vl_logic_vector;
        prs1_int_ready_in: in     vl_logic;
        prs1_fp_ready_in: in     vl_logic;
        prs2_int_ready_in: in     vl_logic;
        prs2_fp_ready_in: in     vl_logic;
        prs3_fp_ready_in: in     vl_logic
    );
    attribute mti_svvh_generic_type : integer;
    attribute mti_svvh_generic_type of TAG_WIDTH : constant is 1;
    attribute mti_svvh_generic_type of \ROB_IDX\ : constant is 1;
end dispatch_unit;
