library verilog;
use verilog.vl_types.all;
entity ROB is
    generic(
        ROB_DEPTH       : integer := 32;
        TAG_WIDTH       : integer := 6;
        \ROB_IDX\       : integer := 5
    );
    port(
        clk             : in     vl_logic;
        rst_n           : in     vl_logic;
        alloc_valid     : in     vl_logic;
        alloc_pc        : in     vl_logic_vector(31 downto 0);
        alloc_rd_arch   : in     vl_logic_vector(4 downto 0);
        alloc_prd       : in     vl_logic_vector;
        alloc_old_prd   : in     vl_logic_vector;
        alloc_fp_rd     : in     vl_logic;
        alloc_is_branch : in     vl_logic;
        alloc_is_jump   : in     vl_logic;
        alloc_jump_rd_val: in     vl_logic_vector(31 downto 0);
        alloc_is_store  : in     vl_logic;
        alloc_use_rd    : in     vl_logic;
        rob_idx         : out    vl_logic_vector;
        rob_full        : out    vl_logic;
        wb0_valid       : in     vl_logic;
        wb0_rob_idx     : in     vl_logic_vector;
        wb0_result      : in     vl_logic_vector(31 downto 0);
        wb0_exc         : in     vl_logic;
        wb1_valid       : in     vl_logic;
        wb1_rob_idx     : in     vl_logic_vector;
        wb1_result      : in     vl_logic_vector(31 downto 0);
        wb1_exc         : in     vl_logic;
        wb2_valid       : in     vl_logic;
        wb2_rob_idx     : in     vl_logic_vector;
        wb2_result      : in     vl_logic_vector(31 downto 0);
        wb2_exc         : in     vl_logic;
        wb3_valid       : in     vl_logic;
        wb3_rob_idx     : in     vl_logic_vector;
        wb3_result      : in     vl_logic_vector(31 downto 0);
        wb3_exc         : in     vl_logic;
        wbs_valid       : in     vl_logic;
        wbs_rob_idx     : in     vl_logic_vector;
        wbs_store_addr  : in     vl_logic_vector(31 downto 0);
        wbs_store_data  : in     vl_logic_vector(31 downto 0);
        wbs_store_mode  : in     vl_logic_vector(2 downto 0);
        commit_valid    : out    vl_logic;
        commit_rd_arch  : out    vl_logic_vector(4 downto 0);
        commit_prd      : out    vl_logic_vector;
        commit_old_prd  : out    vl_logic_vector;
        commit_fp_rd    : out    vl_logic;
        commit_result   : out    vl_logic_vector(31 downto 0);
        commit_pc       : out    vl_logic_vector(31 downto 0);
        commit_use_rd   : out    vl_logic;
        commit_store    : out    vl_logic;
        commit_store_addr: out    vl_logic_vector(31 downto 0);
        commit_store_data: out    vl_logic_vector(31 downto 0);
        commit_store_mode: out    vl_logic_vector(2 downto 0);
        flush           : out    vl_logic;
        flush_pc        : out    vl_logic_vector(31 downto 0);
        cdb0_tag        : out    vl_logic_vector;
        cdb0_valid      : out    vl_logic;
        cdb0_data       : out    vl_logic_vector(31 downto 0);
        cdb1_tag        : out    vl_logic_vector;
        cdb1_valid      : out    vl_logic;
        cdb1_data       : out    vl_logic_vector(31 downto 0);
        cdb2_tag        : out    vl_logic_vector;
        cdb2_valid      : out    vl_logic;
        cdb2_data       : out    vl_logic_vector(31 downto 0);
        cdb3_tag        : out    vl_logic_vector;
        cdb3_valid      : out    vl_logic;
        cdb3_data       : out    vl_logic_vector(31 downto 0);
        rob_empty       : out    vl_logic;
        store_pending   : out    vl_logic
    );
    attribute mti_svvh_generic_type : integer;
    attribute mti_svvh_generic_type of ROB_DEPTH : constant is 1;
    attribute mti_svvh_generic_type of TAG_WIDTH : constant is 1;
    attribute mti_svvh_generic_type of \ROB_IDX\ : constant is 1;
end ROB;
